import Head from 'next/head'
import {BsMoonFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-sky-50">
        <section className="fixed bg-white shadow-sm z-50 px-10 py-2 w-full">
          <nav className="py-10 flex justify-between">
            <h1 className='text-2xl font-bold'>Forest</h1>
            <ul className="flex items-center font-semibold">
              <li><a className='px-2 text-neutral-600 hover:text-sky-500' href="#">About</a></li>
              <li><a className='px-2 text-neutral-600 hover:text-sky-500' href="#">Experience</a></li>
              <li><a className='px-2 text-neutral-600 hover:text-sky-500' href="#">Work</a></li>
              <li><a className='px-2 text-neutral-600 hover:text-sky-500' href="#">Contact</a></li>
            </ul>
            <ul className='flex items-center'>
              <li><BsMoonFill className=' cursor-pointer text-2xl'/></li>
              <li><a className=' bg-sky-500 text-white py-2 px-4 rounded-md ml-8 font-semibold hover:bg-sky-600' href="#">Resume</a></li>
            </ul>
          </nav>
          
        </section>
          

        <section className="absolute mt-44">
          <div className="flex flex-row-reverse m-5">
            <div className="bg-sky-50">
              <h2 className="text-3xl font-bold">Alberto Moreno</h2>
              <h3 className="text-2xl text-sky-500 font-semibold">Frontend Developer</h3>
              <p className="text-lg pt-2">
                I am a Computer Science student at Catholic University of Murcia. Freelancer providing the frontend of webpages. At the moment I am working on multiple development projects
              </p>
            </div>
            <div className="flex flex-col justify-between px-5 text-4xl pt-2">
              <AiFillTwitterCircle/>
              <AiFillLinkedin/>
              <AiFillGithub/>
            </div>
          </div>
          
        </section>
          <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
        <section>

        </section>

        <section>

        </section>
      </main>
    </div>
  )
}
